language: python
python:
  - "2.6"
  #- "2.7"
  #- "3.2"
  #- "3.2"
  #- "3.2"
  
  

install: python setup.py build
script:
  - python setup.py test
#build_image: shippable/minv2
build_image: shippableimages/ubuntu1204_nodejs
commit_container: ragster/rags
cache: true


